### ISSUE TITLE
error running command node c.js

### ISSUE THREAD

**Issue by z115** [walmik/scribbletune#64]
this is what terminal sad:

Pascals-MacBook-Pro:Neuer Ordner 9 surreal1212$ node c.js
module.js:549
    throw err;
    ^

Error: Cannot find module './chord'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/surreal1212/scribbletune/src/index.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Pascals-MacBook-Pro:Neuer Ordner 9 surreal1212$

**Comment by z115** [comment]
Pascals-MacBook-Pro:Neuer Ordner 9 surreal1212$ node c.js
/Users/surreal1212/Desktop/Neuer Ordner 9/c.js:1
(function (exports, require, module, __filename, __dirname) { cd /Users/surreal1212/Desktop/Neuer Ordner 9
                                                                                                  ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Pascals-MacBook-Pro:Neuer Ordner 9 surreal1212$
